@baseUrl=http://localhost:8080

POST {{baseUrl}}/users/ HTTP/1.1
content-type: application/json

{
    "name": "Fulano de Tal",
    "username": "fulaninho",
    "password": "123456"
}
###
POST {{baseUrl}}/tasks/ HTTP/1.1
content-type: application/json
Authorization: Basic fulaninho:123456

{
    "title": "Terminar a criação da API To-Do-List",
    "description": "Programação em Java Spring",
    "priority": "ALTA",
    "startAt": "2024-08-27T08:00:00",
    "endAt": "2024-08-28T23:59:59"
}

###
GET {{baseUrl}}/tasks/
Authorization: Basic fulaninho:123456

###

PUT   {{baseUrl}}/tasks/061ed388-5880-4874-b459-7aaaa1ca334e
content-type: application/json
Authorization: Basic fulaninho:123456

{
    "title": "Alterando o titulo",
    "description": "Programação em Java Spring 2",
    "priority": "MEDIA"
}