@baseUrl=http://localhost:8080

POST {{baseUrl}}/users/ HTTP/1.1
content-type: application/json

{
    "name": "Fulano de Tal",
    "username": "fulaninho",
    "password": "123456"
}
###
POST {{baseUrl}}/tasks/ HTTP/1.1
content-type: application/json
Authorization: Basic fulaninho:123456

{
    "title": "Terminar a criação da API To-Do-List",
    "description": "Programação em Java Spring",
    "priority": "ALTA",
    "startAt": "2024-08-27T08:00:00",
    "endAt": "2024-08-28T23:59:59"
}

###
GET {{baseUrl}}/tasks/
Authorization: Basic fulaninho:123456

###

PUT   {{baseUrl}}/tasks/537245b4-5223-4a9b-9e07-d6688af81c86
content-type: application/json
Authorization: Basic fulaninho:123456

{
    "title": "Alterando o titulo",
    "description": "Programação em Java Spring 2",
    "priority": "MEDIA"
}
###

POST {{baseUrl}}/users/ HTTP/1.1
content-type: application/json

{
    "name": "Usuário de teste",
    "username": "teste",
    "password": "654321"
}
###

PUT   {{baseUrl}}/tasks/537245b4-5223-4a9b-9e07-d6688af81c85
content-type: application/json
Authorization: Basic teste:654321

{
    "title": "Alterando o titulo com um usuário não dono",
    "description": "Não deveria funcionar a alteração por um usuário que não tenha criado a tarega",
    "priority": "ALTA"
}